run:
  go: "1.24"
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gocritic
    - gofmt
    - goimports

linters-settings:
  gocritic:
    enabled-checks:
      - dupImport
      - ifElseChain
      - nestingReduce
      - unnecessaryBlock

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
