version: 2

builds:
  - main: .
    binary: cronado
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

dockers:
  - image_templates:
      - "ghcr.io/teqneers/cronado:{{ .Tag }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.source=https://github.com/teqneers/cronado"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
    dockerfile: docker/Dockerfile.release
  - image_templates:
      - "ghcr.io/teqneers/cronado:{{ .Tag }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.source=https://github.com/teqneers/cronado"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
    goarch: arm64
    dockerfile: docker/Dockerfile.release

docker_manifests:
  - name_template: "ghcr.io/teqneers/cronado:{{ .Tag }}"
    image_templates:
      - "ghcr.io/teqneers/cronado:{{ .Tag }}-amd64"
      - "ghcr.io/teqneers/cronado:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/teqneers/cronado:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/teqneers/cronado:{{ .Tag }}-amd64"
      - "ghcr.io/teqneers/cronado:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/teqneers/cronado:v{{ .Major }}"
    image_templates:
      - "ghcr.io/teqneers/cronado:{{ .Tag }}-amd64"
      - "ghcr.io/teqneers/cronado:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/teqneers/cronado:latest"
    image_templates:
      - "ghcr.io/teqneers/cronado:{{ .Tag }}-amd64"
      - "ghcr.io/teqneers/cronado:{{ .Tag }}-arm64"
    skip_push: "{{ if .Prerelease }}true{{ end }}"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"