FROM golang:1.25-alpine AS go-builder

WORKDIR /opt

RUN apk add --no-cache build-base

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o cronado main.go

FROM alpine:3

WORKDIR /opt

RUN apk add --no-cache ca-certificates tzdata

# Run as root in dev to access Docker socket without permission issues
EXPOSE 8080

ENV GIN_MODE=release

COPY --from=go-builder /opt/cronado ./

CMD ["./cronado", "cron"]
